#!/usr/bin/env ruby

require 'colorize'

# Load lib modules
lib_path = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib_path)

require 'cli'

trap("SIGINT") { exit }

begin
  cli = CLI.new(ARGV)
  cli.run
rescue SystemExit
  raise
rescue => e
  puts e.message.red
  exit 1
end
