name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
#  code-quality: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests with coverage
        run: bundle exec rake spec_with_coverage

      - name: Upload coverage report
        if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && false
        uses: actions/upload-code-coverage@v1
        with:
          file: coverage/coverage.xml
          language: Ruby

